### ISSUE TITLE
Export order results

### ISSUE THREAD

**Issue by fadyham** [saraguirgis/beelish#15]
ensure that the exported order results contains:
- Child Name
- Child Classroom
- Product Variant ordered (by sku or description, or attributes [size, type])
- (stretch goal) Add-ons

**Comment by saraguirgis** [comment]
https://woocommerce.com/products/ordercustomer-csv-export/?utm_source=product&utm_medium=upsell&utm_campaign=wcaddons

https://wordpress.org/plugins/woo-order-export-lite/

http://www.wpallimport.com/woocommerce-order-export/

**Comment by saraguirgis** [comment]
installed https://wordpress.org/plugins/woo-order-export-lite/
