### ISSUE TITLE
Add product description & pictures for Oct-Dec 2017

### ISSUE THREAD

**Issue by fadyham** [saraguirgis/beelish#18]

**Comment by saraguirgis** [comment]
Update short description character length if needed: 

- https://stackoverflow.com/questions/35693954/woocommerce-short-description-excerpt-length

- http://www.kriesi.at/support/topic/limit-the-product-description-length-in-the-overview-product-page-woocommerce/

- https://www.ahsanurrahman.com/short-description-with-limit-in-woocommerce-product-page/

**Comment by saraguirgis** [comment]
Waiting on FareStart to confirm menu description questions
