### ISSUE TITLE
Return to Shop button directs to the wrong page

### ISSUE THREAD

**Issue by fadyham** [saraguirgis/beelish#44]
In the cart page:
https://www.beelish.com/cart/

There's a button called "Return to Shop", which directs the user to:
https://www.beelish.com/shop/

Instead, this should go to:
https://www.beelish.com/wms-test/order/

**Comment by saraguirgis** [comment]
@fadyham I actually don't see that button in my cart.  Just a "Proceed to Checkout" button.  Regardless, I think I put in the right filter to fix the issue.  Whenever you have a chance to look, let me know if it's resolved.

**Comment by fadyham** [comment]
You need to first add an item to the cart
Then view cart
Then remove the item from the cart till it's empty
At that point you'll see the button

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by saraguirgis** [comment]
ohhh got it.  k will try, thank you!


________________________________
